### ISSUE TITLE
It nice to be transform require in this case

### ISSUE THREAD

**Issue by x13771944402** [WarrenJones/vite-plugin-require-transform#1]
In node js,
We can use 
``
  function (resolve) {
     require(['../somefile.vue'], resolve)
  } 
``
how can we transform this code?

**Comment by x13771944402** [comment]
在配置路由的时候，大量使用了这样的写法

const routes = [{
path: '/',
component: function(resolve) {
   require(['../somepath/comp.vue'], resolve)
}
}]
这样的require 怎么转换。

**Comment by WarrenJones** [comment]
看来这种要增加规则了，目前不支持这个。

**Comment by WarrenJones** [comment]
你目前有想到完整的import代替方案么，可以定义一个方案增加规则来适配

**Comment by WarrenJones** [comment]
over 15 days

**Comment by WarrenJones** [comment]
over 15 days

**Comment by W113N23** [comment]
`export const loadView = view => {
  // 路由懒加载
  return () => Promise.resolve(require(`@/views/${view}`).default);
};`现在支持这种方式的了么？
