### ISSUE TITLE
TypeError: requireTransform is not a function

### ISSUE THREAD

**Issue by JayceTsien** [WarrenJones/vite-plugin-require-transform#10]
## Version
```
"vite": "^2.9.8",
"vite-plugin-require-transform": "^1.0.3",
```

## Usage
```js
import requireTransform from 'vite-plugin-require-transform';
// ...
plugins: [
    // react(),
    requireTransform
 ],
// ...
```

## Problem
```
failed to load config from /****/vite.config.js
error during build:
TypeError: requireTransform is not a function
    at file://*****/vite.config.js?t=1658215076374:14:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
```

**Comment by WarrenJones** [comment]
just try it in this way.
import { defineConfig } from 'vite';

/**
 * @param match
 * Regular expression in string or Regexp type,
 *  or a match predicate  (this: vite transform context, code: string, id: file name string) => void
 * @returns transformed code
 */
import requireTransform from 'vite-plugin-require-transform';

export default defineConfig({
  plugins: [
    // passing string type Regular expression
    requireTransform({}),
  ],
});

**Comment by minskiter** [comment]
I also have this problem -- `TypeError: requireTransform is not a function`
vite.config.js
``` js
import { defineConfig } from 'vite'
import { createVuePlugin } from 'vite-plugin-vue2'
import vitePluginRequireTransform from 'vite-plugin-require-transform';
import path from "path"

console.log(vitePluginRequireTransform)

...

```
Command `yarn dev` result:
``` sh
$ vite
{ default: [Function: vitePluginRequireTransform] }
```

Solution:
vite.config.js
``` js
export default defineConfig({
   plugins: [vitePluginRequireTransform.default({})]
})
```

**Comment by terwer** [comment]
> I also have this problem -- `TypeError: requireTransform is not a function` vite.config.js
> 
> ```js
> import { defineConfig } from 'vite'
> import vitePluginRequireTransform from 'vite-plugin-require-transform';
> import path from "path"
> 
> console.log(vitePluginRequireTransform)
> 
> ...
> ```
> 
> Command `yarn dev` result:
> 
> ```shell
> $ vite
> { default: [Function: vitePluginRequireTransform] }
> ```
> 
> Solution: vite.config.js
> 
> ```js
> export default defineConfig({
>    plugins: [vitePluginRequireTransform.default({})]
> })
> ```

Thanks,it worked.
