### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ldv-orbyta** [WarrenJones/vite-plugin-require-transform#11]
**vite.config.ts**

<img width="291" alt="viteconfig" src="https://user-images.githubusercontent.com/88878496/182408546-48e370bb-7b77-4b24-bbca-8993c9562d8e.png">

<img width="529" alt="Cattura" src="https://user-images.githubusercontent.com/88878496/182407192-fdf9a528-75c1-4d29-8bb2-bac4bdcd08d8.PNG">

It doesn't seems to work. Why it didn't transform the files?

**Comment by WarrenJones** [comment]
by default the filter is just ts|tsx. It seems your file  is end with .js. you should past fileRegex to the params which can target this file

**Comment by WarrenJones** [comment]
If this file is in node_modules,I think vite will prebundle it and transform it into esm format which can work well.you'd better post up a minimal repository which can show up the problems so I can help you better

**Comment by ldv-orbyta** [comment]
yes, it was because the filter by default include only the ts/tsx files. I edited my config including /.ts$|.tsx$|.js$|.jsx$/ as regex. 

Now vite says me [vite]: Rollup failed to resolve import "indexof" from "node_modules/component-classes/index.js".                       
I don't think it's a problem of your library, but do you know how to fix it?

Thanks

**Comment by WarrenJones** [comment]
> yes, it was because the filter by default include only the ts/tsx files. I edited my config including /.ts$|.tsx$|.js$|.jsx$/ as regex.
> 
> Now vite says me [vite]: Rollup failed to resolve import "indexof" from "node_modules/component-classes/index.js". I don't think it's a problem of your library, but do you know how to fix it?
> 
> Thanks

It needs your minimal repository that can shows up the problem so I can get all the context
