### ISSUE TITLE
'_vite_plugin_require_transform_fruchterman' has already been declared

### ISSUE THREAD

**Issue by ldv-orbyta** [WarrenJones/vite-plugin-require-transform#12]
SyntaxError: Identifier '_vite_plugin_require_transform_fruchterman' has already been declared (55:6) in /node_modules/@antv/layout/lib/layout/index.js   

Hello again,
do you know why it happens during the project build?
<img width="231" alt="viteconfig" src="https://user-images.githubusercontent.com/88878496/182595285-b6f49c3f-237f-4bb1-8c62-7c950127fae3.png">

Thanks for your support

**Comment by WarrenJones** [comment]
Can you just show the source code of /node_modules/@antv/layout/lib/layout/index.js
