### ISSUE TITLE
p is not iterable

### ISSUE THREAD

**Issue by 150148313** [WarrenJones/vite-plugin-require-transform#18]
Reproduce repositories https://github.com/150148313/vitePluginRequire/tree/main

**Comment by 150148313** [comment]
![image](https://user-images.githubusercontent.com/27761828/187024638-ad86804b-0c44-4308-9544-b959e3ce36df.png)

**Comment by WarrenJones** [comment]
It seems like you don't have any "require" syntax in your repository,so why you use this plugin?

**Comment by WarrenJones** [comment]
and also,you are using "vite-plugin-require",here the plugin is "[vite-plugin-require-transform](https://github.com/WarrenJones/vite-plugin-require-transform)"
