### ISSUE TITLE
入口文件对不上

### ISSUE THREAD

**Issue by yangyanhui1217** [WarrenJones/vite-plugin-require-transform#2]
`package.json` 里面的 `main: "index.js"`, 但是用`npm install` 下来并没有看到有个 `index.js` 文件的

**Comment by yangyanhui1217** [comment]
![image](https://user-images.githubusercontent.com/94613177/156735914-dc248bdb-0bdd-44de-b323-1339b53c94fd.png)

**Comment by WarrenJones** [comment]
已经fix
