### ISSUE TITLE
error when starting dev server: TypeError: requireTransform is not a function

### ISSUE THREAD

**Issue by turnknight** [WarrenJones/vite-plugin-require-transform#20]
error when starting dev server:
TypeError: requireTransform is not a function

**Comment by WarrenJones** [comment]
then just log out what requireTransform is ?

**Comment by dzbo** [comment]
I'm experiencing the same issue. The log returns:

```
{ default: [Function: vitePluginRequireTransform] }
```

It seems to pass calling `default` function:
```js
import requireTransform from 'vite-plugin-require-transform';

export default defineConfig({
  plugins: [
    requireTransform.default({}),
  ],
});
```

But for me this doesn't fix "require" issue, I still see 
<img width="396" alt="CleanShot 2022-09-20 at 12 31 04@2x" src="https://user-images.githubusercontent.com/1100879/191235481-b76c91fd-756a-4f9a-9421-929f8adcc285.png">
when using `npm run preview` in my app.
