### ISSUE TITLE
RequireTransform is not a Function

### ISSUE THREAD

**Issue by lyx-jay** [WarrenJones/vite-plugin-require-transform#23]
Here is the error:

**[vite] requireTransform is not a function**

When i use vite-plugin-require-transform to transform **require** syntax , it doesn't work.

Environment :
1. vite
2. vue2

```js
import { defineConfig } from "vite";
import { createVuePlugin } from "vite-plugin-vue2";
import requireTransform from "vite-plugin-require-transform";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    createVuePlugin(),
    requireTransform({
      fileRegex: /.vue$/,
    }),
  ],
});
```

requireTransform is not a function , it is a object

when I use it in `requrireTransform.default`, it will work normally.

[Minimum reproducing demo](https://codesandbox.io/p/sandbox/vite-vue2-forked-9b9diw?file=%2Fvite.config.ts&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A13%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl95khku20012luip4301gyja%2522%252C%2522openFiles%2522%253A%255B%2522%252Findex.html%2522%252C%2522%252Fsrc%252FApp.vue%2522%252C%2522%252Fvite.config.ts%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl9mtar1k00jvlripcck4g45h%2522%252C%2522key%2522%253A%2522cl9mtaqme01ib3b6ix6uw9936%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl9msxvzh009w3b6hfuph4mry%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5174%252C%2522key%2522%253A%2522cl9mszff500ap3b6ixzcdc1yy%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by WarrenJones** [comment]
import requireTransform from 'vite-plugin-require-transform';

export default defineConfig({
plugins: [
requireTransform.default({}),
],
})

**Comment by WarrenJones** [comment]
try in this way,maybe it's the bundle problem I think.I will fix it in the coming version
