### ISSUE TITLE
开发环境下，未生成souceMap，导致浏览器里的日志打印行 列错乱，debugger 也会出现问题。

### ISSUE THREAD

**Issue by PengQingYao** [WarrenJones/vite-plugin-require-transform#26]

**Comment by PengQingYao** [comment]
把插件配置成pre插件也行哪。 souceMap 由vite去生成。 次插件没生成sourceMap， 倒是把其他插件的sourcemap 给冲掉了。

**Comment by speoth** [comment]
我也遇到了一样的问题，生成的sourcemap文件里面没内容。老哥后来有解决方案吗。

**Comment by speoth** [comment]
不太清楚rollup原理，我把源码拷到工程vite去引用，在transform函数的return里加了个 map:null，看样子不影响整体sourcemap生成了，但估计有点影响。再研究研究

**Comment by PengQingYao** [comment]
> 我也遇到了一样的问题，生成的sourcemap文件里面没内容。老哥后来有解决方案吗。

有解决方案的。  你这样直接返回sourceMap是可以的。但是如果和其他插件一起使用，并且其他插件也有转换的代码的，还是会出现问题。需要做到多个sourceMap串连，babel.transform 有提供一个选项inputSourcemap, 把原始sourcemap 传进去即可。

但是这库用的是parse  tranverse generate包，不能传入inputSourceMap.. 需要调整下结构

**Comment by WarrenJones** [comment]
1.0.6 已经支持了
