### ISSUE TITLE
js 项目不能使用吗？

### ISSUE THREAD

**Issue by Tan-YuanJie** [WarrenJones/vite-plugin-require-transform#27]
启动时报错：TypeError: requireTransform is not a function

**Comment by WarrenJones** [comment]
console.log(requireTransform),just check what is it

**Comment by zhaoqianguo** [comment]
直接  import requireTransform from 'vite-plugin-require-transform';
打印 requireTransform 显示的是一个对象 { default: [Function: vitePluginRequireTransform] }，但是看包里面默认导出的是个函数这是为什么？

**Comment by speoth** [comment]
删除package.json中的type:"module" ，或者把vite.config.js改为vite.config.cjs

**Comment by sanonz** [comment]
@WarrenJones 作者最好加下支持 [https://github.com/vitejs/vite/blob/main/packages/plugin-react/package.json#L13](https://github.com/vitejs/vite/blob/main/packages/plugin-react/package.json#L13)，我看这个问题提 issue 的挺多的

**Comment by terwer** [comment]
> 删除package.json中的`type:"module"` ，因为它会强制将项目中的js以mjs(esm)形式执行
> 
> 当type:"module"打开时，vite.config.js会以mjs形式运行(vite用esbuild编译后创建出的新mjs文件)。 又因为引入的插件本身在node_modules中不受项目type:"module"约束，仍然以commonJs执行，会强制转换成 {default:someValue}的形式(和导出模块使用export.default = someFn 而不是module.export = someFn 有关)。 这似乎是typescript编译的一个默认表现，参考 https://stackoverflow.com/questions/50947208/how-to-compile-typescripts-export-default-into-exports-xxx
> 
> 感兴趣的话可以使用` import someFn from 'file:///Users/yourusername/workspaces/other-project/test.common.js'`，从另一个项目而非node_modules中读取模块，可以获得一样的表现。
> 
> 但如果在当前项目中有某个commonjs的模块。 直接在vite.config.js中import的话就会报错了。
> 
> 详情参考type:"module"的说明

非常感谢，学习了

**Comment by WarrenJones** [comment]
已经支持上了 1.0.5
