### ISSUE TITLE
tree-shaking does not work

### ISSUE THREAD

**Issue by eleven-net-cn** [WarrenJones/vite-plugin-require-transform#29]
tree-shaking does not work when use vite-plugin-require-transform.

e.g.:

```ts
if (process.env.NODE_ENV === 'development') {
  require('axios');
  console.log('hello');
}
```

will transform:

```js
require("axios");
...
```

Even if `process.env.NODE_ENV` is `development`, the `require("axios");` still added at the top, and, the `console.log('hello');` has been removed (treeshaking).

**Comment by WarrenJones** [comment]
can you make sure that this filter has been filtered or not
