### ISSUE TITLE
能支持 一下 类似require('...' + 变量 + '.png')这种格式吗

### ISSUE THREAD

**Issue by yangyanhui1217** [WarrenJones/vite-plugin-require-transform#3]
能支持 一下 类似require('...' + 变量 + '.png')这种格式吗

**Comment by WarrenJones** [comment]
可以具体给一个代码么

**Comment by WarrenJones** [comment]
over 15 days

**Comment by yangyanhui1217** [comment]
> 可以具体给一个代码么

不好意思，最近忙别的，没注意这边，咋关了呢？你要的代码是？

**Comment by WarrenJones** [comment]
> > 可以具体给一个代码么
> 
> 不好意思，最近忙别的，没注意这边，咋关了呢？你要的代码是？

我想了一下，这个插件是将require提升到import，也就是作用域必须是顶层，假如这个变量是在运行时某个函数的作用域生成的，那就无法在import的时候就知道这个变量的内容了

**Comment by yangyanhui1217** [comment]
> > > 可以具体给一个代码么
> > 
> > 
> > 不好意思，最近忙别的，没注意这边，咋关了呢？你要的代码是？
> 
> 我想了一下，这个插件是将require提升到import，也就是作用域必须是顶层，假如这个变量是在运行时某个函数的作用域生成的，那就无法在import的时候就知道这个变量的内容了

目前我针对require('...' + 变量 + '.png')这种格式在我项目里面写了一个插件，实现方式：
解析 require('...' + 变量 + '.png')， 把变量记录下来，然后将 require('../..png')下边所有.png文件都import 进来，然后组将一个map, key是文件路径，value是import 进来的变量名。然后再将require('...' + 变量 + '.png')转成 map['...' + 变量 + '.png']，就可以了
结果：
```
import _$_img_w2GAb9 from '/src/assets/img/icon_word.png?import';
import _$_img_q2GVuC from '/src/assets/img/icon_zip.png?import';
const _$_file_obj_3IanJX = {
   '..\..\assets\img\icon_word.png': _$_img_w2GAb9,
    '..\..\assets\img\icon_zip.png': _$_img_q2GVuC,
}
// 使用变量的地方转成这样
attrs: {
      "src": _$_file_obj_3IanJX["../../assets/img/icon_" + _vm.fileType + ".png"]
}
```
你觉得我这种方式咋样？

**Comment by WarrenJones** [comment]
> > > > 可以具体给一个代码么
> > > 
> > > 
> > > 不好意思，最近忙别的，没注意这边，咋关了呢？你要的代码是？
> > 
> > 
> > 我想了一下，这个插件是将require提升到import，也就是作用域必须是顶层，假如这个变量是在运行时某个函数的作用域生成的，那就无法在import的时候就知道这个变量的内容了
> 
> 目前我针对require('...' + 变量 + '.png')这种格式在我项目里面写了一个插件，实现方式： 解析 require('...' + 变量 + '.png')， 把变量记录下来，然后将 require('../..png')下边所有.png文件都import 进来，然后组将一个map, key是文件路径，value是import 进来的变量名。然后再将require('...' + 变量 + '.png')转成 map['...' + 变量 + '.png']，就可以了 结果：
> 
> ```
> import _$_img_w2GAb9 from '/src/assets/img/icon_word.png?import';
> import _$_img_q2GVuC from '/src/assets/img/icon_zip.png?import';
> const _$_file_obj_3IanJX = {
>    '..\..\assets\img\icon_word.png': _$_img_w2GAb9,
>     '..\..\assets\img\icon_zip.png': _$_img_q2GVuC,
> }
> // 使用变量的地方转成这样
> attrs: {
>       "src": _$_file_obj_3IanJX["../../assets/img/icon_" + _vm.fileType + ".png"]
> }
> ```
> 
> 你觉得我这种方式咋样？

可以的，这种插件不好兼容，建议能手动改写的就直接手动改写了

**Comment by jetBn** [comment]
> > > > 可以具体给一个代码么
> > > 
> > > 
> > > 不好意思，最近忙别的，没注意这边，咋关了呢？你要的代码是？
> > 
> > 
> > 我想了一下，这个插件是将require提升到import，也就是作用域必须是顶层，假如这个变量是在运行时某个函数的作用域生成的，那就无法在import的时候就知道这个变量的内容了
> 
> 目前我针对require('...' + 变量 + '.png')这种格式在我项目里面写了一个插件，实现方式： 解析 require('...' + 变量 + '.png')， 把变量记录下来，然后将 require('../..png')下边所有.png文件都import 进来，然后组将一个map, key是文件路径，value是import 进来的变量名。然后再将require('...' + 变量 + '.png')转成 map['...' + 变量 + '.png']，就可以了 结果：
> 
> ```
> import _$_img_w2GAb9 from '/src/assets/img/icon_word.png?import';
> import _$_img_q2GVuC from '/src/assets/img/icon_zip.png?import';
> const _$_file_obj_3IanJX = {
>    '..\..\assets\img\icon_word.png': _$_img_w2GAb9,
>     '..\..\assets\img\icon_zip.png': _$_img_q2GVuC,
> }
> // 使用变量的地方转成这样
> attrs: {
>       "src": _$_file_obj_3IanJX["../../assets/img/icon_" + _vm.fileType + ".png"]
> }
> ```
> 
> 你觉得我这种方式咋样？

有发出来吗 ？
