### ISSUE TITLE
requireTransform is not a function

### ISSUE THREAD

**Issue by wspj** [WarrenJones/vite-plugin-require-transform#33]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/31205291/207302347-dc16ecc3-ec3b-46d2-b9c9-b831e98e9560.png">
requireTransform is not a function

**Comment by WarrenJones** [comment]
try requireTransform.default

**Comment by pitis** [comment]
I think this has become an issue now with vite 4, because with vite 3 it worked ok

**Comment by gthdweb** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/26158236/210523090-57ccc5f0-e4ed-498f-8a8f-7ab43aa81061.png">
遇到了同样的问题

**Comment by gthdweb** [comment]
> try requireTransform.default

Thats Ok,but have tip no type
<img width="968" alt="image" src="https://user-images.githubusercontent.com/26158236/210523978-ee6abd97-8da3-45df-ae4b-892205837f78.png">

**Comment by WarrenJones** [comment]
it's fixed in version 1.0.5.
