### ISSUE TITLE
vue2.6.12 and use ali-oss@6.10.0, vite build failed

### ISSUE THREAD

**Issue by smallButVeryStrong** [WarrenJones/vite-plugin-require-transform#36]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/21958022/216013437-31d12af2-ecac-44f0-9a87-eda9ebd116c8.png">

**Comment by WarrenJones** [comment]
This seems you need to defined a importPathHandler pass as params,just checkout the readme file and read the case 3 you can figure it out
