### ISSUE TITLE
why dist/index.d.ts is empty

### ISSUE THREAD

**Issue by gary-zhu** [WarrenJones/vite-plugin-require-transform#40]
import vitePluginRequireTransform from 'vite-plugin-require-transform'
plugins: [
            vitePluginRequireTransform({
                fileRegex: /.ts$|.tsx$/
            })
        ]

This expression is not callable.
  Type 'typeof import("c:/Users/garwood/Documents/security-validate-web/node_modules/vite-plugin-require-transform/dist/index")' has no call signatures.ts

**Comment by gary-zhu** [comment]
version 1.0.9

**Comment by gary-zhu** [comment]
![image_2023_02_16T12_17_17_784Z](https://user-images.githubusercontent.com/46038375/219533107-7384d945-4997-4fa2-81b6-c93d2aa623c1.png)
![image_2023_02_16T12_17_10_424Z](https://user-images.githubusercontent.com/46038375/219533150-dcd9e765-823f-4d6d-a620-f653d9868448.png)

**Comment by tpluscode** [comment]
Also manifests itself as 

> TS1192: Module '"/node_modules/vite-plugin-require-transform/dist/index"' has no default export.

**Comment by feizhaojun** [comment]
I revert to version 1.0.8, and resolve it.
