### ISSUE TITLE
为什么vite-plugin-require-transform这么写会报错，怎么解决

### ISSUE THREAD

**Issue by dj49846917** [WarrenJones/vite-plugin-require-transform#41]
![image](https://user-images.githubusercontent.com/30486590/224532942-f9e3693a-8c34-4827-bdc4-c69f2fdf103a.png)

"vite": "^4.1.4",
"vite-plugin-require-transform": "^1.0.9",
"typescript": "^4.9.5",
"vue": "^3.2.47",

**Comment by WarrenJones** [comment]
更新一下最新版，fix了
