### ISSUE TITLE
The requested module '/config/env.ts' does not provide an export named 'default

### ISSUE THREAD

**Issue by TryChai** [WarrenJones/vite-plugin-require-transform#42]
when I use this plugin to deal wiith the problem of 'require',it was create a new error 
![image](https://user-images.githubusercontent.com/30064871/224557228-9e0f1199-7972-4981-aa39-23fe6e41c7c4.png)
![image](https://user-images.githubusercontent.com/30064871/224557243-1d8ac40f-b2fe-4330-b24e-bd94b0679ea3.png)
![image](https://user-images.githubusercontent.com/30064871/224557259-e94eefd6-0948-476b-8380-94261d565742.png)
you can see it has the new problem

**Comment by WarrenJones** [comment]
can you create a minimal repository

**Comment by WarrenJones** [comment]
you should import {requireTransform} in this way
