### ISSUE TITLE
 ERROR  [_vite_plugin_require_transform_] traverse is not a function   

### ISSUE THREAD

**Issue by iwangx** [WarrenJones/vite-plugin-require-transform#45]
"typescript": "4.9.5",
"vite": "4.2.0",
"vite-plugin-require-transform": "1.0.12"

**Comment by WarrenJones** [comment]
can you create a minimal repository or show out the code that how you use the plugin

**Comment by luciferyue** [comment]
Is it because your new version doesn't use “require” escape？

Your "vite-plugin-require-transform" version "1.0.9",dist output 
const traverse_1 = __importDefault(require("@babel/traverse"));

Your "vite-plugin-require-transform" version "1.0.12",dist output
import traverse from "@babel/traverse";

node Not supported import；

**Comment by 1046616906** [comment]
@luciferyue   
我也遇到这问题,怎么解决呢？

**Comment by luciferyue** [comment]
> @luciferyue 我也遇到这问题,怎么解决呢？
试用"vite-plugin-require-transform":"1.0.9"的版本就行，你可以看他1.0.12打包后的输出是用的import导出，而1.0.9是用的require

**Comment by luciferyue** [comment]
> > Is it because your new version doesn't use “require” escape？
> > Your "vite-plugin-require-transform" version "1.0.9",dist output const traverse_1 = __importDefault(require("@babel/traverse"));
> > Your "vite-plugin-require-transform" version "1.0.12",dist output import traverse from "@babel/traverse";
> > node Not supported import；
> 
> it works good on my project,would you offer a minimal repository so that I can try to fix it out

> @luciferyue 我也遇到这问题,怎么解决呢？

或者你使用的时候，require引入，不要用import。如果使用 import 对该库进行导入，则首次寻找 package.json module 字段引入，否则引入 main 字段。他1.0.9只有一个导出，但是1.0.12的时候，导出两个main和module，你还用import，他优先找的是module，里面用的是import，这样node不认，你启动的时候是跑的node环境。

**Comment by luciferyue** [comment]
> > Is it because your new version doesn't use “require” escape？
> > Your "vite-plugin-require-transform" version "1.0.9",dist output const traverse_1 = __importDefault(require("@babel/traverse"));
> > Your "vite-plugin-require-transform" version "1.0.12",dist output import traverse from "@babel/traverse";
> > node Not supported import；
> 
> it works good on my project,would you offer a minimal repository so that I can try to fix it out

你的插件应该是只在node环境跑的，你1.0.9的版本， package.json 里只有一个导出，"main": "dist/index.js"。而1.0.12产物更规范了，区分了main和module。但是这个插件的使用场景是在node环境.
下面是你的输出代码：
dist/index.js => var import_traverse = __toESM(require("@babel/traverse"));
index.mjs=> import traverse from "@babel/traverse";
我使用 import requireTransform from "vite-plugin-require-transform";
他会优先找"module": "dist/index.mjs",所以才报的错。

我是通过node脚本，启动的vite
const viteConfig = generateViteConfig() ;   //封装的获取配置方法
await createServer(viteConfig);

**Comment by gthdweb** [comment]
遇到了相同的问题
![image](https://user-images.githubusercontent.com/26158236/233036042-089070df-1adc-404f-8cc2-e334335a6524.png)
<img width="540" alt="image" src="https://user-images.githubusercontent.com/26158236/233036092-92610159-f838-4725-8c9f-6d8fd7935661.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/26158236/233036194-94c8425d-554f-4ac0-9ffa-88bccfd49ba8.png">

**Comment by WarrenJones** [comment]
> 遇到了相同的问题 ![image](https://user-images.githubusercontent.com/26158236/233036042-089070df-1adc-404f-8cc2-e334335a6524.png) <img alt="image" width="540" src="https://user-images.githubusercontent.com/26158236/233036092-92610159-f838-4725-8c9f-6d8fd7935661.png"> <img alt="image" width="729" src="https://user-images.githubusercontent.com/26158236/233036194-94c8425d-554f-4ac0-9ffa-88bccfd49ba8.png">

我的场景没问题，可以提供一下仓库吗？我修复一下

**Comment by gthdweb** [comment]
> 
https://github.com/gthdweb/requrieTest

**Comment by earlAchromatic** [comment]
Same problem for me using Vite 3

**Comment by l-monninger** [comment]
Same

**Comment by AlDantefox** [comment]
Same problem in last Vite

**Comment by lgyytm** [comment]
需要插件改下逻辑
@babel/traverse默认吐的是default
![image](https://github.com/WarrenJones/vite-plugin-require-transform/assets/21163261/789ddc44-5bdd-4232-b2bd-ef7f096509c8)

**Comment by lgyytm** [comment]
> 需要插件改下逻辑 @babel/traverse默认吐的是default ![image](https://user-images.githubusercontent.com/21163261/240111228-789ddc44-5bdd-4232-b2bd-ef7f096509c8.png)

![image](https://github.com/WarrenJones/vite-plugin-require-transform/assets/21163261/6d63fa1b-82b5-4034-99fe-37e92bfbeca8)

**Comment by lgyytm** [comment]
@WarrenJones traverse exports an object, not a default function

**Comment by alexkreidler** [comment]
Same problem:
```
8:27:24 AM [vite] Internal server error: traverse is not a function
  Plugin: _vite_plugin_require_transform_
  File: /root/c2/vegafusion/vegafusion-demos/apps/editor-vite/src/main.ts
      at TransformContext.transform (file:///root/c2/vegafusion/vegafusion-demos/apps/editor-vite/node_modules/.pnpm/vite-plugin-require-transform@1.0.12/node_modules/vite-plugin-require-transform/dist/index.mjs:24:9)
      at Object.transform (file:///root/c2/vegafusion/vegafusion-demos/apps/editor-vite/node_modules/.pnpm/vite@4.3.2/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:42863:44)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///root/c2/vegafusion/vegafusion-demos/apps/editor-vite/node_modules/.pnpm/vite@4.3.2/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:53342:29)
```
Relevant example code:
```js
var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var tasks_pb = require('./tasks_pb.js');
```

**Comment by terwer** [comment]
+1
1.0.12必现此问题，期待修复。

**Comment by WarrenJones** [comment]
sorry for the late reply and long time support ,the bug has been fixed in the lastest version

**Comment by marwie** [comment]
Hi, I just got this error in a sveltekit project using vite 4.3.0 and require-transform 1.0.18

**Comment by WarrenJones** [comment]
> Hi, I just got this error in a sveltekit project using vite 4.3.0 and require-transform 1.0.18
> 
> ```js
> TypeError: traverse is not a function
>     at TransformContext.transform (file:///.../node_modules/vite-plugin-require-transform/dist/index.mjs:26:7)
>     at Object.transform (file:///.../node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:44)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async loadAndTransform (file:///.../node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29) {
> ```

cc @JannikGM

**Comment by WarrenJones** [comment]
> Hi, I just got this error in a sveltekit project using vite 4.3.0 and require-transform 1.0.18
> 
> ```js
> TypeError: traverse is not a function
>     at TransformContext.transform (file:///.../node_modules/vite-plugin-require-transform/dist/index.mjs:26:7)
>     at Object.transform (file:///.../node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:44)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async loadAndTransform (file:///.../node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29) {
> ```
install the newest version,it's fixed

**Comment by WarrenJones** [comment]
> Isn't that `1.0.18` ?

1.0.19

**Comment by marwie** [comment]
Ah ok npm said it was published 7 hours ago (wasnt visible for me yesterday) - good to hear then
