### ISSUE TITLE
Vite2.9.9 + Vue2 +vite-plugin-require-transform: "^1.0.17" 的项目中，npm run build的时候报错Unexpected token (1:42) - make sure this is an expression.

### ISSUE THREAD

**Issue by maoyining** [WarrenJones/vite-plugin-require-transform#47]
Vite2.9.9 + Vue2 +vite-plugin-require-transform: "^1.0.17" 的项目中，npm run build构建的时候报错

报错内容：
```
[_vite_plugin_require_transform_] Unexpected token (1:42) - make sure this is an expression.
> 1 | (_vite_plugin_require_transform_validator/)
```
配置如下：
```
import { defineConfig } from 'vite';
import { createVuePlugin } from 'vite-plugin-vue2';
import Markdown from 'vite-plugin-md';
import requireTransform from 'vite-plugin-require-transform';
import { resolve } from 'path';

export default defineConfig({
  plugins: [
    createVuePlugin({ include: [/\.vue$/, /\.md$/, /\.cur$/] }),
    Markdown(),
    requireTransform({
      fileRegex: /.js$|.vue$/
    })
  ],
  global: {},
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '~': resolve(__dirname, './packages'),
      source: resolve(__dirname, './source'),
      vue$: 'vue/dist/vue.esm.js'
    }
  }
});

```

**Comment by maoyining** [comment]
npm run dev 的时候是正常的，只有构建的时候报错

**Comment by WarrenJones** [comment]
can you post a minimal reproduce repository?

**Comment by zjluse** [comment]
> Vite2.9.9 + Vue2 +vite-plugin-require-transform: "^1.0.17" 的项目中，npm run build 构建的时候报错
> 
> 报错内容：
> 
> ```
> [_vite_plugin_require_transform_] Unexpected token (1:42) - make sure this is an expression.
> > 1 | (_vite_plugin_require_transform_validator/)
> ```
> 
> 配置如下：
> 
> ```
> import { defineConfig } from 'vite';
> import { createVuePlugin } from 'vite-plugin-vue2';
> import Markdown from 'vite-plugin-md';
> import requireTransform from 'vite-plugin-require-transform';
> import { resolve } from 'path';
> 
> export default defineConfig({
>   plugins: [
>     createVuePlugin({ include: [/\.vue$/, /\.md$/, /\.cur$/] }),
>     Markdown(),
>     requireTransform({
>       fileRegex: /.js$|.vue$/
>     })
>   ],
>   global: {},
>   resolve: {
>     alias: {
>       '@': resolve(__dirname, 'src'),
>       '~': resolve(__dirname, './packages'),
>       source: resolve(__dirname, './source'),
>       vue$: 'vue/dist/vue.esm.js'
>     }
>   }
> });
> ```

This is my problem too, just delete fileRegex: /.ts$|.tsx$|.vue$|$/, just fine

**Comment by icefire24** [comment]
![image](https://github.com/WarrenJones/vite-plugin-require-transform/assets/67216778/e623e8f3-d4aa-47a7-be5c-467ecef0706d)
i also encountered  the same problem only in build,how i fixed it

**Comment by kuankuan2007** [comment]
I had the same problem

**Comment by WarrenJones** [comment]
> I had the same problem

can you show out the source code of the error file? I guess it's causing of the naming of the variable

**Comment by jackZmym** [comment]
> > 我有同样的问题
> 
> 你能显示错误文件的源代码吗？我猜这是变量命名的原因

3: import * as _vite_plugin_require_transform_get_intrinsic_0 from "get-intrinsic";
4: var GetIntrinsic = _vite_plugin_require_transform_get_intrinsic_0.default || _vite_plugin_require_transform_get_intri...
5: import * as _vite_plugin_require_transform_./_1 from "./";
                                              ^
6: var callBind = _vite_plugin_require_transform_./_1.default || _vite_plugin_require_transform_./_1;
7: var $indexOf = callBind(GetIntrinsic('String.prototype.indexOf'));

**Comment by WarrenJones** [comment]
> > > 我有同样的问题
> > 
> > 
> > 你能显示错误文件的源代码吗？我猜这是变量命名的原因
> 
> 3: import * as _vite_plugin_require_transform_get_intrinsic_0 from "get-intrinsic"; 4: var GetIntrinsic = _vite_plugin_require_transform_get_intrinsic_0.default || _vite_plugin_require_transform_get_intri... 5: import * as _vite_plugin_require_transform_./_1 from "./"; ^ 6: var callBind = _vite_plugin_require_transform_./_1.default || _vite_plugin_require_transform_./_1; 7: var $indexOf = callBind(GetIntrinsic('String.prototype.indexOf'));

just checkout the readme file and look through case3, it can help solve your problem
