### ISSUE TITLE
Import statements are in reverse order

### ISSUE THREAD

**Issue by JannikGM** [WarrenJones/vite-plugin-require-transform#53]
We have some CSS which is affected by https://github.com/vitejs/vite/issues/3924

We should add the imports in order of appearance. 
Imports are correctly iterated in map insertion order.
However, they are added in reverse order due to `ast.program.body.unshift`.

There might be additional issues when mixing `require` and `import`, but we can probably ignore them for now.

**Comment by ghost** [comment]
#54 has massively improved the CSS for us (where order is important), but now we still have a bunch of styling bugs (which went unnoticed during development and testing of #54).
I'll try to debug this further in the near future.

Among them is a bug with `"@material-ui/core": "^4.11.4",`:

### Working Result (how it should look like)
<img width="56" alt="Screenshot 2023-07-20 at 16 16 39" src="https://github.com/WarrenJones/vite-plugin-require-transform/assets/72194488/3b8d6316-fcf4-4f13-9a08-bfc1b7094474">

### Broken Result (what it currently looks like)
<img width="56" alt="Screenshot 2023-07-20 at 16 16 27" src="https://github.com/WarrenJones/vite-plugin-require-transform/assets/72194488/266d617d-d910-48de-9d50-c448ca067371">

### Broken CSS
<img width="304" alt="Screenshot 2023-07-20 at 16 16 17" src="https://github.com/WarrenJones/vite-plugin-require-transform/assets/72194488/bfff911f-7d60-44a5-818a-414c54908ab9">

### Broken HTML
<img width="380" alt="Screenshot 2023-07-20 at 16 08 38" src="https://github.com/WarrenJones/vite-plugin-require-transform/assets/72194488/388fa1aa-d9af-4f7f-9025-0060c976d34f">

**Comment by ghost** [comment]
We solved the problem above with `StylesProvider` from mui: https://github.com/mui/material-ui/issues/11843#issuecomment-534982194.
We already had a hack using `JssProvider` from react-jss, but that didn't work in Vite (not sure what it did for webpack).

I'm not sure why there's a difference between webpack and vite for this or why the `JssProvider` didn't work, but that's not important for us, now that it works.

So I believe everything works as intended now 👍
