### ISSUE TITLE
builderror

### ISSUE THREAD

**Issue by delisteam** [WarrenJones/vite-plugin-require-transform#6]
开发环境的时候正常，打包构建的时候如果fileRegex写了/.js$|.jsx$|.vue$/就报错
vite.config.js:
defineConfig({
    plugins: [
      requireTransform({
        fileRegex: /.js$|.jsx$|.vue$/,
      })
    ],
})
只写.vue正常打包
requireTransform({
        fileRegex: /.vue$/,
  }),

错误日志
✓ 516 modules transformed.
[_vite_plugin_require_transform_] Unexpected token (1:33) - make sure this is an expression.
> 1 | (_vite_plugin_require_transform_./)
    |                                  ^
file: C:/Users/Administrator/Desktop/xx/node_modules/_call-bind@1.0.2@call-bind/callBound.js:1:33
error during build:
SyntaxError: Unexpected token (1:33) - make sure this is an expression.
> 1 | (_vite_plugin_require_transform_./)
    |                                  ^
    at instantiate (...\node_modules\_@babel_parser@7.17.10@@babel\parser\lib\index.js:72:32)
    at constructor (...\_@babel_parser@7.17.10@@babel\parser\lib\index.js:358:12)
    at Parser.raise (...\node_modules\_@babel_parser@7.17.10@@babel\parser\lib\index.js:3335:19)

**Comment by WarrenJones** [comment]
can you  provide a minimal repo link that can reproduce the problem you ran into?or just list the source code that cause the error

**Comment by yuguaa** [comment]
> t constructor (..._@babel_parser@7.17.10@@babel\parser\lib\index.js:358怎么解决的呀，请问

**Comment by yuguaa** [comment]
> > [#6 (comment)](https://github.com/WarrenJones/vite-plugin-require-transform/issues/6#issue-1226494550) 请问怎么解决的啊
> 
> 可以提供下报错的文件或者截图么

antd引入的一个插件报错了，配了external不打包他了

**Comment by baoweijun** [comment]
你们解决了吗？搞不定

**Comment by baoweijun** [comment]
> 开发环境的时候正常，打包构建的时候如果fileRegex写了/.js$|.jsx$|.vue$/就报错 vite.config.js: defineConfig({ plugins: [ requireTransform({ fileRegex: /.js$|.jsx$|.vue$/, }) ], }) 只写.vue正常打包 requireTransform({ fileRegex: /.vue$/, }),
> 
> 错误日志 ✓ 516 modules transformed. [_vite_plugin_require_transform_] Unexpected token (1:33) - make sure this is an expression.
> 
> > 1 | (_vite_plugin_require_transform_./)
> > |                                  ^
> > file: C:/Users/Administrator/Desktop/xx/node_modules/_call-bind@1.0.2@call-bind/callBound.js:1:33
> > error during build:
> > SyntaxError: Unexpected token (1:33) - make sure this is an expression.
> > 1 | (_vite_plugin_require_transform_./)
> > |                                  ^
> > at instantiate (...\node_modules_@babel_parser@7.17.10@@babel\parser\lib\index.js:72:32)
> > at constructor (..._@babel_parser@7.17.10@@babel\parser\lib\index.js:358:12)
> > at Parser.raise (...\node_modules_@babel_parser@7.17.10@@babel\parser\lib\index.js:3335:19)

你解决了吗

**Comment by zkk2019** [comment]
需要下载一个包 @rollup/plugin-commonjs
然后在 plugins 第一项使用

import commonjs from '@rollup/plugin-commonjs'

plugins: [
			commonjs(),
]
