### ISSUE TITLE
[plugin:_vite_plugin_require_transform_] Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by jetBn** [WarrenJones/vite-plugin-require-transform#7]

**Comment by WarrenJones** [comment]
can you provide a minimal repo link that can reproduce the problem you ran into?or just list the source code that cause the error

**Comment by jetBn** [comment]
It may i use require dynamic. #3

**Comment by jetBn** [comment]
has solutions ? about use  require dynamic it like it.
![image](https://user-images.githubusercontent.com/26957220/167240796-2a0a921f-3e78-4639-8a42-b47be5a2b960.png)

**Comment by WarrenJones** [comment]
Yes,it can be resolve,I will fix it in the next version

**Comment by jetBn** [comment]
What time was next version publish ??

**Comment by WarrenJones** [comment]
maybe in the coming week

**Comment by jetBn** [comment]
It can use in .vue file template？
