### ISSUE TITLE
exclusion option

### ISSUE THREAD

**Issue by qinghuangdao** [WarrenJones/vite-plugin-require-transform#9]
Can you add an exclusion option？
Thank you very much (ever so much) (most sincerely) (indeed) (from the bottom of my heart)

**Comment by WarrenJones** [comment]
> Can you add an exclusion option？ Thank you very much (ever so much) (most sincerely) (indeed) (from the bottom of my heart)

Can you just describe it more specific,better to show a scenario so I can get what exactlly need to do
